### ISSUE TITLE
This  will  get your  abend0c7  (as  requested) 

### ISSUE THREAD

**Issue by john19508** [moshix/abendanalysis#1]
Add this  to  your  abendasm .jcl  job   and all  is  well

//GO.OUTDD    DD SYSOUT=H,DCB=(LRECL=121,BLKSIZE=1210)

**Comment by john19508** [comment]
Oops  i  should  have  seen  your  video  and   comments  before  "solving"    your  problem.
BTW  there  where  ample  hints in the  joblog   before  doing the  dump analysis   to  fix  your  problem.. (syntax  in the assembler and logic  error (outdd) in the  jcl..

**Comment by moshix** [comment]
Yes, of course there are hints in the job log. That's not the point at all. The point is how to learn to read a dump. 

thanks

M
